src/Entity/PhotoDansCorbeille.php
<?php

namespace App\Entity;

use App\Repository\DansCorbeilleRepository;
use DateInterval;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DansCorbeilleRepository::class)
 * @ORM\Table(name="corbeille")
 */
class PhotoDansCorbeille
{
    ///**
    // *
    // * @ORM\GeneratedValue
    // * @ORM\Column(type="integer")
    // */
    //private $id;

    /**
	 * @ORM\Id
     * @ORM\OneToOne(targetEntity=Photo::class, inversedBy="corbeille", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $photo;

    /**
     * @ORM\Column(type="date")
     */
    private $date_corbeille;


    public function __construct() {
    	$this->date_corbeille = new \DateTimeImmutable();
	}

	//public function getId(): ?int
    //{
    //    return $this->id;
    //}

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDateCorbeille(): ?\DateTimeInterface
    {
        return $this->date_corbeille;
    }

    public function getDateSuppression(): ?\DateTimeInterface{
    	return (clone $this->getDateCorbeille())->add(new DateInterval('P30D'));
	}

	public function getTempsAvantSuppression(){
    	$diff = (new DateTime())->setTime(0,0)->diff($this->getDateSuppression());
    	return $diff->invert ? -$diff->days : $diff->days;
	}

    public function setDateCorbeille(\DateTimeInterface $date_corbeille): self
    {
        $this->date_corbeille = $date_corbeille;

        return $this;
    }
}

src/Controller/CorbeilleController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use App\Entity\PhotoDansCorbeille;
use App\Entity\User;
use App\Repository\DansCorbeilleRepository;
use App\Repository\PhotoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CorbeilleController extends AbstractController
{
    public function index(): Response
    {
		$em = $this->getDoctrine()->getManager();

		/** @var DansCorbeilleRepository $repoUser */
		//$repoCorbeille = $em->getRepository(PhotoDansCorbeille::class);
		/** @var PhotoRepository $repoUser */
		//$repoPhoto = $em->getRepository(Photo::class);

		/** @var User $user */
		$user = $this->getUser();

		$photosInCorbeille = $user->getPhotosInCorbeille();
		/** @var Photo $photo */
		foreach($photosInCorbeille as $photo){
			if($photo->getCorbeille()->getTempsAvantSuppression() <= 0 ){
				$em->remove($photo);
				$photosInCorbeille->removeElement($photo);
			}
		}

		$em->flush();

        return $this->render('corbeille/index.html.twig', [
			'photos' => $photosInCorbeille,
        ]);
    }

    public function getPhoto(int $photo): Response {
		/** @var User $user */
		$user = $this->getUser();

		if($user === null){
			return new Response("Unauthorized", 401);
		}

		$em = $this->getDoctrine();

		/** @var Photo $photo retrieving asked photo */
		$photo = $em->getRepository(Photo::class)->find($photo);
		if($photo === null){
			return new Response(null, 404);
		}

		$photoUser = $photo->getUser();
		// vérifie le droit d'accès
		if($user !== $photoUser) {
			return new Response(null, 403);
		}

		return $this->render("corbeille/includes/detail.photo.html.twig", [
			"photo" => $photo
		]);

	}
}

templates/corbeille/includes/detail.photo.html.twig
{% extends 'includes/photo-view.html.twig' %}

{% block threePointsMenuContent %}
    <button type="button" class="dropdown-item d-flex justify-content-between align-items-baseline restore-photo">
        Restaurer <i class="fas fa-undo-alt ml-2"></i>
    </button>
    <button type="button" class="dropdown-item text-danger d-flex justify-content-between align-items-baseline delete-photo">
        Supprimer définitivement <i class="fas fa-trash-alt ml-2"></i>
    </button>
{% endblock %}

{% block cardBody %}
    {{ parent() }}
    <p class="card-text">
        <small>
            Mise dans la corbeille le {{ photo.corbeille.dateCorbeille|date('d/m/Y') }}<br>
            <span class="text-danger">
                Sera supprimée le {{ photo.corbeille.dateSuppression|date('d/m/Y') }}
                (dans {{ photo.corbeille.tempsAvantSuppression }} jour{{ photo.corbeille.tempsAvantSuppression > 1 ? 's' :'' }})
            </span>
        </small>
    </p>
{% endblock %}