src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AlbumRepository::class)
 */
class Album
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="albums")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $titre;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="album")
     */
    private $photos;


    public function __construct() {
    	$this->date_creation = new DateTime();
     	$this->photos = new ArrayCollection();
	}

	public function getId(): ?int
	{
		return $this->id;
	}

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCreation(): ?DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhotos(): Collection
    {
        $photos_visibles = new ArrayCollection();
        foreach($this->photos as $photo) {
            if(!$photo->getCorbeille())
                $photos_visibles[] = $photo;
        }
        return $photos_visibles;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setAlbum($this);
        }

        return $this;
    }

    public function getP1Photo()
    {
        return $this->getPhotos()->get(0);
    }

    public function getP2Photo()
    {
        return $this->getPhotos()->get(1);
    }

    public function getP3Photo()
    {
        return $this->getPhotos()->get(2);
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getAlbum() === $this) {
                $photo->setAlbum(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Entity\Photo;
use App\Entity\Tag;
use App\Entity\User;
use App\Form\FilterType;
use App\Form\PhotoType;
use App\Repository\AlbumRepository;
use App\Repository\PhotoRepository;
use App\Repository\UserRepository;
use Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination;
use Knp\Component\Pager\Paginator;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
	/**
	 * @param PaginatorInterface $paginator
	 * @param string $pseudo
	 * @param int $page
	 * @param int|null $photo
	 * @return Response
	 */
    public function index(PaginatorInterface $paginator, string $pseudo, int $page=1, int $photo=null)
    {
		$em = $this->getDoctrine()->getManager();

		/****************************/
		/* gestion de l'utilisateur */
        /****************************/

    	/** @var UserRepository $repoUser */
    	$repoUser = $em->getRepository(User::class);

    	/** @var User $profileUser */
    	$profileUser = $repoUser->findOneByPseudo($pseudo);
		/** @var User $user */
		$user = $this->getUser();

		/* if user with pseudo $pseudo does not exist */
		if(is_null($profileUser)) {
			throw $this->createNotFoundException("Pas d'utilisateur avec le pseudo \"" . $pseudo.'"');
		}

		/********************************/
		/* gestion des photos du profil */
        /********************************/

		/** @var PhotoRepository $repoPhoto */
		$repoPhoto = $em->getRepository(Photo::class);
		if($photo!==null){
			$page = $repoPhoto->getPage($repoPhoto->find($photo));
		}

		/* récupère les photos de l'utilisateur */
		$queryBuilder = $repoPhoto->findDisplayableBy(['user'=>$profileUser], ['datePublication' => 'desc']);
        $repoTag = $em->getRepository(Tag::class);
        $tagList =  $repoTag->findTagText($queryBuilder);

		/* création du formulaire de filtres des photos */
        $filterForm = $this->createForm(FilterType::class, null, [
            'attr' => ['id' => 'filter-form'],
            'tagTextList' => $tagList,
            'user' => $profileUser
        ]);

		/* crée le paginateur */
		/** @var SlidingPagination $paginated_photos */
		$paginated_photos = $paginator->paginate($queryBuilder, $page, 9,[
			Paginator::PAGE_OUT_OF_RANGE => Paginator::PAGE_OUT_OF_RANGE_FIX
		]);
		$paginated_photos->setTemplate("/profile/includes/template.pagination.html.twig");

		/************************/
		/* création du contexte */
		/************************/
		$context = [
			'profileUser' => $profileUser,
			'photos' => $paginated_photos,
			'page' => $paginated_photos->getCurrentPageNumber(),
			'displayedPhoto' => $photo,
            'order' => 'DESC',
            'filterForm' => $filterForm->createView()
		];

        /*******************************************/
		/* gestion du formulaire de photo et d'ami */
        /*******************************************/
		if($user === $profileUser){
			$photo = new Photo();

			$form = $this->createForm(PhotoType::class, $photo, [
				'method' => 'POST',
				'attr' => ['id' => 'add_photo_form'],
			]);
			$context['form'] = $form->createView();

			return $this->render('profile/owner.profile.html.twig', $context);
		} else {
			$btnToDisplay = null;
			if($user && $user->getAmis()->contains($profileUser)){
				$relation = $user->getRelationFromAmi($profileUser);
				if($relation->getStatut()){ // statut == true -> demande deja acceptée
					$btnToDisplay = 'remove';
				} else {
					if($relation->getUser1() === $user){ // demande sortante
						$btnToDisplay = 'cancel';
					} else { //demande entrante
						$btnToDisplay = 'answer';
					}
				}
			} else {
				$btnToDisplay = 'add';
			}

            $context['btnAmi'] = $btnToDisplay;

			return $this->render('profile/base.profile.html.twig', $context);
		}
    }
}

templates/profile/includes/detail.album.html.twig
<div class="border border-darktheme">
    <div id="parameter-menu-container" class="row mx-0 pt-2 mb-5">
        <div class="col-6">
            <a id="exit" class="py-2 pr-0 text-primary" href="{{ path('album.grid.get', {pseudo: album.user.pseudo, page:1}) }}">
                {# exit #}
                <i class="fas fa-arrow-left" title="fermer l'album"></i>
            </a>
        </div>
        {% if album.getPhotos is not empty %}
        <div class="col-6 d-flex justify-content-end">
            <a id="album-modifier-photos" class="text-center" type="button" href="#">
                <div class="d-inline-flex align-items-center">
                    {# trier #}
                    <i class="fas fa-sort-amount-down"></i>
                </div>
            </a>
        </div>
        {% endif %}
    </div>

    <div id="titre-album-row" class="row justify-content-center align-items-center mx-0 my-auto">

        <div class="col-auto">
            <h2>{{ album.titre }}</h2>
        </div>

        {% if app.user and album.user.pseudo == app.user.pseudo %}
            <div class="col-auto">
                <div class="dropdown">
                    <a class="text-primary align-center dropdown-toggle" href="#" id="dropdownMenuAlbum" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <h5><i class="fas fa-ellipsis-h"></i></h5>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuAlbum">
                        <a class="dropdown-item edit-album-btn" href="#" data-url="{{ path('album.edit', {album_id: album.id}) }}" data-toggle="modal" data-target="#modalEditAlbumForm" >Modifier le titre</a>
                        <a class="dropdown-item delete-album-btn" href="#" data-url="{{ path('album.delete', {album_id: album.id}) }}" data-toggle="modal" data-target="#modalDeleteAlbumForm">Supprimer l'album</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    <div id="album-photo-row" class="row justify-content-center pb-5 h-100 my-5 mx-0">
        {% for photo in photo_list %}
            <div class="col-sm-4 col-album mb-2">
                <a class="thumbnail" data-toggle="modal" data-target="#modalShowAlbumPhoto">
                    <div class="album-photo-container position-relative overflow-hidden" data-url="{{ path('photo.get', {photo_id: photo.id}) }}">
                        <div class="img-cover w-100 h-100 position-absolute"
                             style="background-image: url('{{ asset('content/img/photo/'~photo.fichier) }}');">
                        </div>
                        {% if app.user and photo.user.pseudo == app.user.pseudo %}
                            <div class="action-album-photo-cover d-flex flex-column h-100 w-100 position-absolute p-3 text-white justify-content-between">
                                <h5 class="action-album-photo">{{ photo.titre|e }}</h5>
                                <span class="action-album-photo">{{ photo.datePublication|date('d/m/Y H\\hi') }}</span>
                            </div>
                        {% endif %}
                    </div>
                </a>
            </div>
        {% else %}
            <div class="col-12 d-flex flex-column justify-content-center align-self-center text-center mx-auto my-auto">
                <h3 class=display-3">Cet album est vide</h3>
                <p>
                    Ne serait-il point temps de le remplir ?
                </p>
            </div>
        {% endfor %}


        <nav id="album-photo-pagination" class="pagination-nav d-flex w-100 justify-content-center" aria-label="pagination-nav">
            {{ knp_pagination_render(photo_list) }}
        </nav>
    </div>
</div>

templates/profile/includes/detail.photo.html.twig
{% extends 'includes/photo-view.html.twig' %}

{% block threePointsMenuContent %}
    {% if photo.user == app.user %}
        <button id="editPhoto" class="dropdown-item" data-toggle="modal" data-target="#show_tile_modal">
            Modifier
        </button>
        <button id="editAlbumPhoto" class="dropdown-item" data-toggle="modal" data-target="#modalEditAlbumPhoto">
            {% if photo.album is empty %}
                Ajouter dans un album
            {% else %}
                Changer d'album
            {% endif %}
        </button>
        <button id="deletePhoto" class="dropdown-item" data-toggle="modal" data-target="#modalDeletePhotoConfirmation">
            Mettre dans la corbeille
        </button>
    {% endif %}
    <button id="sharePhoto" class="dropdown-item">
        Partager
    </button>
    {% if photo.user != app.user and app.user != null %}
        <button id="reportPhoto" type="button" class="dropdown-item">
            Signaler
        </button>
    {% endif %}
{% endblock %}

templates/profile/includes/filter.form.html.twig
{{ form }}

templates/profile/includes/grid.album.html.twig
<div id="parameter-menu-container" class="row mb-3">
    {% if app.user and profileUser == app.user %}
        <div class="col-6 mr-auto">
            <a id="add-album-btn" class="text-center btn btn-outline-primary" type="button" data-toggle="modal" data-target="#modalAddAlbumForm" data-url="{{ path('album.add') }}">
                <div class="d-inline-flex align-items-center">
                    {# add #}
                    <i class="fas fa-plus mr-1"></i> Ajouter un album
                </div>
            </a>
        </div>
    {% endif %}
    {% if albums is not empty %}
        <div class="col-6 ml-auto d-flex justify-content-end">
            {% if order == 'ASC' %}
                <a id="sort-albums-btn" class="text-center" type="button" href="{{ path('album.grid.get', {pseudo: profileUser.pseudo, page:page, order: 'DESC'}) }}" data-order="{{ order }}">
                    <div class="d-inline-flex align-items-center">
                        {# trier #}
                        <i class="fas fa-sort-alpha-down"></i>
                    </div>
                </a>
            {% else %}
                <a id="sort-albums-btn" class="text-center" type="button" href="{{ path('album.grid.get', {pseudo: profileUser.pseudo, page:page, order: 'ASC'}) }}">
                    <div class="d-inline-flex align-items-center">
                        {# trier #}
                        <i class="fas fa-sort-alpha-up"></i>
                    </div>
                </a>
            {% endif %}
        </div>
    {% endif %}
</div>

<div id="album-list-container" class="position-relative">
    <div id="album-row" class="row justify-content-center pb-3">
        {% for album in albums %}
            <div class="col-sm-4 mb-2 col-album">
                <a class="thumbnail" href="{{ path('album.get', {pseudo: album.user.pseudo, album_id: album.id}) }}">
                    <div class="album-container position-relative overflow-hidden">
                        <div class="d-flex flex-column w-100 h-100 album position-absolute justify-content-center">
                            <div class="row album-cover-container w-100 h-75 mx-0 flex-nowrap">
                                <div id="album-cover-1" class="album-cover col-8 h-75 position-absolute p-0 rounded border-darktheme bg-light bg-darkmode-dark"
                                        {% if album.getP1Photo %}
                                            style="background-image: url('{{ asset('content/img/photo/'~album.getP1Photo.fichier) }}');"
                                        {% endif %}
                                ></div>
                                <div id="album-cover-2" class="album-cover col-6 h-75 offset-4 position-absolute p-0 rounded border-darktheme bg-light bg-darkmode-dark"
                                        {% if album.getP2Photo %}
                                            style="background-image: url('{{ asset('content/img/photo/'~album.getP2Photo.fichier) }}');"
                                        {% endif %}
                                ></div>
                                <div id="album-cover-3" class="album-cover col-6 h-75 offset-6 position-absolute p-0 rounded border-darktheme bg-light bg-darkmode-dark"
                                        {% if album.getP3Photo %}
                                            style="background-image: url('{{ asset('content/img/photo/'~album.getP3Photo.fichier) }}');"
                                        {% endif %}
                                ></div>
                            </div>
                            <div class="row w-100 h-25 mx-0 justify-content-between">
                                <h5 class="col-12 mb-0">{{ album.titre }}</h5>
                                <p class="col-auto"><small class="text-muted">{{ album.dateCreation|date('d/m/Y') }}</small></p>
                                <p class="col-auto text-end"><small class="text-muted">{{ album.photos.count }} photos</small></p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% else %}
            <div class="col-sm-4 mb-2 col-album">
                Pas de page à cet index :/
            </div>
        {% endfor %}

        {% if albums is not empty %}
            <nav id="album-pagination" class="pagination-nav d-flex w-100 justify-content-center" aria-label="pagination-nav">
                {{ knp_pagination_render(albums) }}
            </nav>
        {% endif %}
    </div>
</div>

templates/profile/includes/grid.photo.html.twig
{% for photo in photos %}
    <div class="col-4 img-col">
        <div class="img-container rounded border border-darktheme position-relative overflow-hidden">
            <a class="stretched-link" href="#">
                <div class="img"
                     style="background-image: url('{{ asset('content/img/photo/'~photo.fichier|e('url')) }}');"
                     data-photo-id="{{ photo.id|e('html_attr') }}">
                </div>
            </a>
            <div class="position-absolute w-100 h-100 img-overlay p-3 text-light d-flex flex-column justify-content-between">
                <h5>{{ photo.titre|e }}</h5>
                <span class="small">{{ photo.datePublication|date('d/m/Y H\\hi') }}</span>
            </div>
        </div>
    </div>

{% endfor %}

<nav class="pagination-nav d-flex w-100 justify-content-center" aria-label="pagination-nav">
    {{ knp_pagination_render(photos) }}
</nav>

templates/profile/includes/not-connected.photo.html.twig
<div class="text-center">
    <h3>Ce compte est malheureusement privé 😕</h3>
    <h5>Connectez-vous pour voir ses photos ou envoyer une demande en ami</h5>
</div>

templates/profile/includes/not-friend.photo.html.twig
<div class="text-center">
    <h3>Oh non, cette personne n'est pas (encore) votre ami(e) 😔</h3>
    <h5>Envoyez-lui une demande dès maintenant si ce n'est pas déjà fait</h5>
</div>

templates/profile/includes/template.pagination.html.twig
{#
/**
 * @file
 * Twitter Bootstrap v4-beta.2 Sliding pagination control implementation.
 *
 * View that can be used with the pagination module
 * from the Twitter Bootstrap CSS Toolkit
 * https://getbootstrap.com/docs/4.4/components/pagination/
 */
#}
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }} mb-0">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" data-page="{{ previous }}" href="#">
                        <i class="fas fa-angle-left"></i>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">
                        <i class="fas fa-angle-left"></i>
                    </span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" data-page="1" href="#">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" data-page="2" href="#">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page }}"  href="#">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ pageCount-1 }}" href="#">
                                {{ pageCount-1 }}
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ pageCount }}" href="#">
                        {{ pageCount }}
                    </a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" data-page="{{ next }}" href="#">
                        <i class="fas fa-angle-right"></i>
                    </a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}